# Generated by Django 4.2 on 2023-05-05 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudvotaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_candidato', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('partido', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'candidaturas',
            },
        ),
        migrations.CreateModel(
            name='Ciudadanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_Electoral', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('Edad', models.CharField(max_length=3)),
                ('curp', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ciudadanos',
            },
        ),
        migrations.CreateModel(
            name='Votos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Voto', models.CharField(max_length=50)),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudvotaciones.candidaturas')),
            ],
            options={
                'db_table': 'votos',
            },
        ),
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.AddField(
            model_name='candidaturas',
            name='clave_Electoral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudvotaciones.ciudadanos'),
        ),
    ]
