# Generated by Django 4.2 on 2023-05-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudvotaciones', '0003_rename_edad_ciudadanos_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votos',
            old_name='id_candidato',
            new_name='Patidoseleccionado',
        ),
        migrations.RemoveField(
            model_name='votos',
            name='id_Voto',
        ),
    ]
