# Generated by Django 4.2 on 2023-05-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudvotaciones', '0004_rename_id_candidato_votos_patidoseleccionado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votos',
            old_name='Patidoseleccionado',
            new_name='votacion',
        ),
    ]
